In [101]:
import pandas as pd
import json

In [102]:
lines = []
for line in open('homework.json', 'r'):
    lines.append(json.loads(line))

In [103]:
data = pd.DataFrame(lines)

In [104]:
data.head()

emotion_0 emotion_1 emotion_2 emotion_3 emotion_4 emotion_5 emotion_6  \
0       0.0       0.0       0.0       0.0       0.0       1.0       0.0   
1       0.0       0.0       0.0       0.0       0.0       1.0       0.0   
2       0.0       0.0        -2       0.0       0.0       0.0       0.0   
3       0.0       1.0       0.0       1.0       0.0       1.0       0.0   
4       0.0       0.0       0.0       0.0       0.0       1.0       0.0   

  emotion_7 emotion_8 emotion_9  \
0       0.0       0.0         1   
1       0.0       0.0         1   
2       0.0       0.0         1   
3       1.0       0.0         1   
4       0.0       0.0         1   

                                            headline  \
0           Parenting Lessons From a Partial Eclipse   
1                                       On Catalonia   
2      A Spark of Romance Under Fluorescent Lighting   
3  Apple Removes Apps From China Store That Help ...   
4  Commerce Secretary’s Offshore Ties to Putin ‘C...   

                                             summary worker_id  
0  I don’t do partiality. Maybe it was finally ti...  95524929  
1  Catalan lawmakers declared independence from S...  30266977  
2  Rose Burlingham, an art dealer and writer, mar...  54197764  
3  The world’s most valuable company appears to h...  41177265  
4  Wilbur Ross, the commerce secretary, retained ...  56518865

In [106]:
data.isnull().sum()

emotion_0    0
emotion_1    0
emotion_2    0
emotion_3    0
emotion_4    0
emotion_5    0
emotion_6    0
emotion_7    0
emotion_8    0
emotion_9    0
headline     0
summary      0
worker_id    0
dtype: int64

In [11]:
data.shape

(93758, 13)

In [105]:
# drop nulls from the data
data = data.dropna()

In [107]:
# value counts for each column
for c in data.columns:
    print "---- %s ---" % c
    print data[c].value_counts()

---- emotion_0 ---
0.0      84012
1.0       8958
cat        220
-1         204
fnord      193
-2         171
Name: emotion_0, dtype: int64
---- emotion_1 ---
0.0      84197
1.0       8800
-1         197
-2         192
cat        190
fnord      182
Name: emotion_1, dtype: int64
---- emotion_2 ---
0.0      85629
1.0       7364
-1         209
fnord      193
-2         183
cat        180
Name: emotion_2, dtype: int64
---- emotion_3 ---
0.0      86011
1.0       6985
fnord      205
-2         195
-1         190
cat        172
Name: emotion_3, dtype: int64
---- emotion_4 ---
0.0      83796
1.0       9211
-2         197
cat        193
fnord      182
-1         179
Name: emotion_4, dtype: int64
---- emotion_5 ---
0.0      57089
1.0      35891
-1         202
-2         196
cat        196
fnord      184
Name: emotion_5, dtype: int64
---- emotion_6 ---
0.0      89602
1.0       3451
fnord      194
-2         180
-1         166
cat        165
Name: emotion_6, dtype: int64
---- emotion_7 ---
0.0     

In [108]:
# get rid of any string values

data['emotion_0'] = data['emotion_0'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 
data['emotion_1'] = data['emotion_1'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 
data['emotion_2'] = data['emotion_2'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 
data['emotion_3'] = data['emotion_3'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 
data['emotion_4'] = data['emotion_4'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 
data['emotion_5'] = data['emotion_5'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 
data['emotion_6'] = data['emotion_6'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 
data['emotion_7'] = data['emotion_7'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 
data['emotion_8'] = data['emotion_8'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 
data['emotion_9'] = data['emotion_9'].apply(lambda x: "0.0" if 'cat' in str(x) else("0.0" if 'fnord' in str(x) else x)) 

In [109]:
data.iloc[:,0:10] = data.iloc[:,0:10].astype("float")

In [110]:
# boilerplate code for forming bag of words vectors from headlines
import nltk
import numpy
import re
from nltk.corpus import stopwords
set(stopwords.words('english'))

BoW = []
def tokenize(sentences):
    words = []
    for sentence in sentences:
        w = word_extraction(sentence)
        words.extend(w)
        
    words = sorted(list(set(words)))
    return words

def word_extraction(sentence):
    ignore = ['a', "the", "is"]
    words = re.sub("[^\w]", " ",  sentence).split()
    cleaned_text = [w.lower() for w in words if w not in ignore]
    return cleaned_text    
    
def generate_bow(allsentences):    
    vocab = tokenize(allsentences)
    print("Word List for Document \n{0} \n".format(vocab));

    for sentence in allsentences:
        words = word_extraction(sentence)
        bag_vector = numpy.zeros(len(vocab))
        for w in words:
            for i,word in enumerate(vocab):
                if word == w: 
                    bag_vector[i] += 1
                    
        print("{0} \n{1}\n".format(sentence,numpy.array(bag_vector)))
        BoW.append(numpy.array(bag_vector))
        
    
allsentences = data.headline.str.encode('utf-8').sample(1000)

generate_bow(allsentences)

Return of the ’80s! Synth-Pop Bands Stage a Middle-Aged Comeback 
[0. 0. 0. ... 0. 0. 0.]

Looking for a London Vacation Rental? We Tried the Plum Guide 
[0. 0. 0. ... 0. 0. 0.]

Senator McCain’s Health, and America’s 
[0. 0. 0. ... 0. 0. 0.]

Why You Need the Flu Shot Every Year 
[0. 0. 0. ... 0. 0. 0.]

The National Crackup 
[0. 0. 0. ... 0. 0. 0.]

Trump Plays Whack-a-Tax 
[0. 0. 0. ... 0. 0. 0.]

In America’s Heartland, the Nazi Sympathizer Next Door 
[0. 0. 0. ... 0. 0. 0.]

How Did NBC Miss Out on a Harvey Weinstein Exposé? 
[0. 0. 0. ... 0. 0. 0.]

Ricki Shenfeld, Stuart Tishman 
[0. 0. 0. ... 0. 0. 0.]

A Violinist as Riveting in Silence as in Sound 
[0. 0. 0. ... 0. 0. 0.]

Listen to ‘The Daily’: Al Franken and the Democrats 
[0. 0. 0. ... 0. 0. 0.]

For Ravaged Vieques, Solitude, Once an Allure, Is Now a Curse 
[0. 0. 0. ... 0. 0. 0.]

Meet Maya Reik, the 19-Year-Old Israeli Designer Showing in Milan 
[0. 0. 0. ... 0. 0. 0.]

House Republicans’ Hard-Line Immigration Stand Cla

In [111]:
vocab = tokenize(allsentences)

In [ ]:
for i, voc in enumerate(vocab):
    print i, voc

In [112]:
bow_df = pd.DataFrame(BoW)

In [ ]:
bow_w_headlines = pd.concat([allsentences.reset_index(), bow_df], axis=1)
bow_w_headlines2 = bow_w_headlines.merge(data, on='headline', how='left')
bow_w_headlines2 = bow_w_headlines2.dropna()

In [114]:
allsentences.reset_index().head()

index                                           headline
0  77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...
1  36043  These Americans Hated the Health Law. Until th...
2  87375  Australia, Apple, Minnesota: Your Thursday Bri...
3  16131  Yankees, Peeking at the Red Sox, Will Soon Get...
4  64344  Trump Lawyer ‘Vehemently’ Denies Russian Collu...

In [120]:
bow_w_headlines2

index                                           headline    0    1  \
0      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
1      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
2      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
3      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
4      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
5      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  NaN  NaN   
6      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  NaN  NaN   
7      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  NaN  NaN   
8      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  NaN  NaN   
9      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  NaN  NaN   
10     36043  These Americans Hated the Health Law. Until th...  NaN  NaN   
11     36043  These Americans Hated the Health Law. Until th...  NaN  NaN   
12     36043  These Americans Hated the Health Law. Until th...  NaN  NaN   
13     36043  These Americans Hated the Health Law. Until th...  NaN  NaN   
14     36043  These Americans Hated the Health Law. Until th...  NaN  NaN   
15     36043  These Americans Hated the Health Law. Until th...  NaN  NaN   
16     36043  These Americans Hated the Health Law. Until th...  NaN  NaN   
17     36043  These Americans Hated the Health Law. Until th...  NaN  NaN   
18     36043  These Americans Hated the Health Law. Until th...  NaN  NaN   
19     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
20     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
21     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
22     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
23     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
24     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
25     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
26     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
27     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
28     87375  Australia, Apple, Minnesota: Your Thursday Bri...  NaN  NaN   
29     16131  Yankees, Peeking at the Red Sox, Will Soon Get...  NaN  NaN   
...      ...                                                ...  ...  ...   
10720  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10721  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10722  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10723  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10724  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10725  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10726  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10727  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10728  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10729  84829  California Today: Renewed Scrutiny of Sanctuar...  NaN  NaN   
10730  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
10731  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
10732  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
10733  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
10734  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
10735  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
10736  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
10737  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
10738  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
10739  24411  Australia Gripped by Decades of Sexual Abuse o...  NaN  NaN   
107

In [135]:
bowshape = bow_w_headlines2.shape[1]

bow_w_headlines2.iloc[:,2:bowshape-2].head()
bow_w_headlines2.iloc[:,2:bowshape-2] = bow_w_headlines2.iloc[:,2:bowshape-2].astype("float")

bow_w_headlines_ft_matrix = bow_w_headlines2.groupby('headline').mean().reset_index()

In [136]:
bow_w_headlines_ft_matrix

headline         index   0   1  \
0                                                       55774.000000 NaN NaN   
1                                                   -1  51948.000000 NaN NaN   
2                                                   -2  42567.000000 NaN NaN   
3                           10 Things to Do Now in NYC  40230.000000 NaN NaN   
4                           10 Things to Do in NYC Now  19228.000000 NaN NaN   
5    11 Powerful Women We Met Around the World in 2017  59210.000000 NaN NaN   
6                         11 of Our Best Weekend Reads  18251.000000 NaN NaN   
7    2 American Families Are Mourned After Plane Cr...  60042.000000 NaN NaN   
8    2 Police Officers Are Charged in Assault of Me...  56288.000000 NaN NaN   
9    2 Suspects Held in Plot to Kill the U.K. Prime...  30670.000000 NaN NaN   
10               20 Must-Read Books on the Vietnam War  47424.000000 NaN NaN   
11                             2018 Grammy Nominations  40668.000000 NaN NaN   
12   21st Century Fox Pressed by Investment Group t...  91433.000000 NaN NaN   
13   23 Women Accuse Former Queens Priest of Abusin...  90093.000000 NaN NaN   
14                5 Last-Minute Labor Day Destinations  23243.000000 NaN NaN   
15   7 Shows for President Trump to Watch on His Va...  85328.000000 NaN NaN   
16   7 Stopovers that Make Adding a Day (or More) t...  82252.000000 NaN NaN   
17                                   7 Wishes for 2018  61084.000000 NaN NaN   
18       9/11: Finding Answers in Ashes 16 Years Later  64105.000000 NaN NaN   
19   A Defender of the Constitution, With No Legal ...  88803.000000 NaN NaN   
20   A Hot Microphone Catches Senate Gossip, but No...  24547.000000 NaN NaN   
21              A Love Match, Orchestrated by the Moms  57798.000000 NaN NaN   
22   A Month Has Passed Since Trump Declared an Opi...  75094.000000 NaN NaN   
23                        A Plan to Decrease Fertility  16228.000000 NaN NaN   
24   A Post-Obama Democratic Party in Search of Itself  64411.000000 NaN NaN   
25   A Strict Olympic Crackdown on Russian Logos an...  24748.333333 NaN NaN   
26   A Top Republican Vows a Vote on Health Care, b...   2774.000000 NaN NaN   
27      A Violinist as Riveting in Silence as in Sound  93545.000000 NaN NaN   
28   A Watch With Snob Appeal for Under $1,000? Six...  45148.000000 NaN NaN   
29                                A Word to the Hungry  43944.000000 NaN NaN   
..                                                 ...           ...  ..  ..   
606                 Who Deserves a Ticker-Tape Parade?  21618.000000 NaN NaN   
607   Who Gains From the Tax Plan? Economists Face Off  71479.000000 NaN NaN   
608  Who Needs the Hamptons When You Have the Parke...  32788.000000 NaN NaN   
609                               Who Pays Estate Tax?  48259.000000 NaN NaN   
610       Why Are the Baby Boomers in Such a Bad Mood?  70676.000000 NaN NaN   
611                     Why Democrats Need Wall Street   9034.500000 NaN NaN   
612                       Why Do I Give on the Subway?  34566.500000 NaN NaN   
613       Why No One Knows What Will Happen in Alabama  38566.000000 NaN NaN   
614  Why Ousting Nawaz Sharif Sets a Dangerous Prec...  62177.000000 NaN NaN   
615   Why So Many People Choose the Wrong Health Plans  53844.000000 NaN NaN   
616  Why We Published the Name of a Covert C.I.A. O...  20485.000000 NaN NaN   
617               Why You Need the Flu Shot Every Year  58153.000000 NaN NaN   
618                Why the Race for Mayor Looks So Sad  34439.000000 NaN NaN   
619  Wildfires in Northern California Force Mass Ev...  50697.000000 NaN NaN   
620  Will Banning Russia From the 2018 Winter Games...  14593.000000 NaN NaN   
621  Will a Corporate Tax Holiday Give Workers Anyt...  67654.000000 NaN NaN   
622  With Christian Pulisic Driving, United States ...  69942.000000 NaN NaN   
623  With Racket and Voice, Kevin Anderson Looks to...   6411.000000 NaN NaN   
624     World Cup 2018 Draw: Live Updates and 

In [125]:
bow_w_headlines2

index                                           headline    0    1  \
0      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
1      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
2      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
3      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
4      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
5      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
6      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
7      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
8      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
9      77934  Hugh Freeze Abruptly Resigns as Ole Miss Footb...  0.0  0.0   
10     36043  These Americans Hated the Health Law. Until th...  0.0  0.0   
11     36043  These Americans Hated the Health Law. Until th...  0.0  0.0   
12     36043  These Americans Hated the Health Law. Until th...  0.0  0.0   
13     36043  These Americans Hated the Health Law. Until th...  0.0  0.0   
14     36043  These Americans Hated the Health Law. Until th...  0.0  0.0   
15     36043  These Americans Hated the Health Law. Until th...  0.0  0.0   
16     36043  These Americans Hated the Health Law. Until th...  0.0  0.0   
17     36043  These Americans Hated the Health Law. Until th...  0.0  0.0   
18     36043  These Americans Hated the Health Law. Until th...  0.0  0.0   
19     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
20     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
21     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
22     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
23     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
24     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
25     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
26     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
27     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
28     87375  Australia, Apple, Minnesota: Your Thursday Bri...  0.0  0.0   
29     16131  Yankees, Peeking at the Red Sox, Will Soon Get...  0.0  0.0   
...      ...                                                ...  ...  ...   
10720  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10721  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10722  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10723  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10724  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10725  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10726  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10727  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10728  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10729  84829  California Today: Renewed Scrutiny of Sanctuar...  0.0  0.0   
10730  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
10731  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
10732  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
10733  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
10734  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
10735  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
10736  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
10737  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
10738  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
10739  24411  Australia Gripped by Decades of Sexual Abuse o...  0.0  0.0   
107

In [ ]:
bow_w_headlines_ft_matrix = bow_w_headlines2.groupby('headline').mean().reset_index()

In [31]:
bow_w_headlines_ft_matrix.iloc[:,2:3351].head()


0     1     2     3     4     5     6     7     8     9     ...  3339  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

   3340  3341  3342  3343  3344  3345  3346  3347  3348  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 3349 columns]

In [100]:
bow_w_headlines_ft_matrix.iloc[:,bow_w_headlines_ft_matrix.shape[1]-10:bow_w_headlines_ft_matrix.shape[1]+10].head()

emotion_0  emotion_1  emotion_2  emotion_3  emotion_4  emotion_5  \
0   0.108108   0.091892   0.070270   0.048649   0.113514   0.383784   
1   0.111111   0.000000   0.000000   0.000000   0.111111   0.333333   
2   0.070175   0.100877   0.070175   0.039474   0.061404   0.385965   
3   0.089286   0.107143   0.023810   0.059524   0.119048   0.428571   
4   0.128440   0.000000   0.091743   0.009174   0.027523   0.660550   

   emotion_6  emotion_7  emotion_8  emotion_9  
0   0.027027   0.172973   0.216216   0.983784  
1   0.000000   0.000000   0.555556   1.000000  
2   0.039474   0.122807   0.267544   0.982456  
3   0.000000   0.125000   0.184524   0.994048  
4   0.000000   0.000000   0.155963   0.972477

In [33]:
bowshape = bow_w_headlines2.shape[1]
X = bow_w_headlines_ft_matrix.iloc[:,2:bowshape-2-10]
y = bow_w_headlines_ft_matrix.iloc[:,bowshape-2-10:bowshape-2]

###  Baseline Predictions with Linear Regression Model

In [34]:
from sklearn.model_selection import train_test_split

# Split X and y into X_
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [35]:
from sklearn.linear_model import LinearRegression

regression_model = LinearRegression()
regression_model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [ ]:
# coefficients("tokens") in bow dataset on regression model
for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, regression_model.coef_[0][idx]))

In [38]:
intercept = regression_model.intercept_[0]

print("The intercept for our model is {}".format(intercept))

The intercept for our model is 0.105749969314


In [39]:
regression_model.score(X_test, y_test)

-0.06679821932023658

In [40]:
from sklearn.metrics import mean_squared_error

y_predict = regression_model.predict(X_test)

regression_model_mse = mean_squared_error(y_predict, y_test)

regression_model_mse

0.02359541855770604

In [41]:
x_test2 =X_test.reset_index()

In [42]:
x_test2.rename(columns={'index':'level_0'}, 
                 inplace=True)

In [43]:
x_test2.head()

level_0    0    1    2    3    4    5    6    7    8  ...  3339  3340  \
0      496  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1      107  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2       66  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3      159  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4      511  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

   3341  3342  3343  3344  3345  3346  3347  3348  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 3350 columns]

### Comparing headlines and linear regression model predictions 

In [49]:
sanity2 = pd.concat([sanity, pd.DataFrame(y_predict)], axis=1)
sanity2.iloc[:,3350:3361].head()

headline         0         1  \
0  The Rohingya in Myanmar: How Years of Strife G... -0.028614  0.191259   
1                 Caitlin Henningsen, Russell Rennie  0.105729  0.072688   
2  Angela Merkel Declared Winner of German Electi...  0.080571  0.052986   
3     Dozens Feared Dead in Fire at Philippines Mall  0.079687  0.159288   
4  Tina Howe Copes With Caregiving and Other Late...  0.025736  0.012118   

          2         3         4         5         6         7         8  \
0  0.021091  0.151993  0.152596  0.426010 -0.014197  0.455976  0.218503   
1  0.108860  0.037943  0.071093  0.330176  0.057603  0.093333  0.273276   
2  0.101788 -0.019616  0.197057  0.389021  0.000706 -0.006167  0.271794   
3  0.009320  0.122406 -0.018139  0.239737  0.082647  0.372581  0.111787   
4  0.145201  0.074175  0.107978  0.315555  0.041515  0.145940  0.269203   

          9  
0  1.012764  
1  0.972976  
2  0.989934  
3  0.952058  
4  1.024831

In [46]:
sanity = x_test2.merge(bow_w_headlines_ft_matrix2, on='level_0', how = 'inner')
sanity.head()

level_0    0    1    2    3    4    5    6    7    8  ...  3340  3341  \
0      496  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1      107  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2       66  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3      159  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4      511  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

   3342  3343  3344  3345  3346  3347  3348  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

                                            headline  
0  The Rohingya in Myanmar: How Years of Strife G...  
1                 Caitlin Henningsen, Russell Rennie  
2  Angela Merkel Declared Winner of German Electi...  
3     Dozens Feared Dead in Fire at Philippines Mall  
4  Tina Howe Copes With Caregiving and Other Late...  

[5 rows x 3351 columns]

In [45]:
bow_w_headlines_ft_matrix2 = bow_w_headlines_ft_matrix.reset_index()
bow_w_headlines_ft_matrix2 = bow_w_headlines_ft_matrix2[['level_0','headline']] 

In [50]:
import math

math.sqrt(regression_model_mse)

0.1536080029090478

In [51]:
data.headline.iloc[5000:5001,].reset_index().headline[0]

u'Obesity Was Rising as Ghana Embraced Fast Food. Then Came KFC.'

In [54]:
unseen_doc = []
sentence = "Obesity Was Rising as Ghana Embraced Fast Food. Then Came KFC."
words = word_extraction(sentence)
bag_vector_sample = numpy.zeros(len(vocab))
for w in words:
    for i,word in enumerate(vocab):
                if word == w: 
                    bag_vector_sample[i] += 1
                    
print("{0} \n{1}\n".format(sentence,numpy.array(bag_vector_sample)))
unseen_doc.append(numpy.array(bag_vector_sample))
unseen_doc = pd.DataFrame(unseen_doc)

Obesity Was Rising as Ghana Embraced Fast Food. Then Came KFC. 
[0. 0. 0. ... 0. 0. 0.]



In [55]:
for i in range(len(y.columns.tolist())):
    print y.columns.tolist()[i], ": ", regression_model.predict(unseen_doc).tolist()[0][i]

emotion_0 :  0.200272218448
emotion_1 :  0.0841800243889
emotion_2 :  0.0736660560588
emotion_3 :  0.0596826461061
emotion_4 :  0.0668950896335
emotion_5 :  0.197489272146
emotion_6 :  0.127773610976
emotion_7 :  0.00309720922604
emotion_8 :  0.315987600438
emotion_9 :  0.991675806327


## Predictions on Random Forest Regressor & KNN Regressor 

In [73]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)

rf = RandomForestRegressor(n_estimators=100, random_state=10)
knn = KNeighborsRegressor()
preds = {}
for model_name, model in zip(['RandomForestRegressor', 'KNearestNeighbors'], [rf, knn]):
    model.fit(X_train, y_train)
    preds[model_name] = model.predict(X_test)

In [74]:
# Evaluating the Algorithm
from sklearn import metrics
for k in preds:
    print("{} performance:".format(k))
    print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, preds[k]))  
    print('Mean Squared Error:', metrics.mean_squared_error(y_test, preds[k]))  
    print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, preds[k])))
    print " "


KNearestNeighbors performance:
('Mean Absolute Error:', 0.1050682730641888)
('Mean Squared Error:', 0.021858531106878996)
('Root Mean Squared Error:', 0.14784630907425114)
 
RandomForestRegressor performance:
('Mean Absolute Error:', 0.10012406890983001)
('Mean Squared Error:', 0.020903782940572626)
('Root Mean Squared Error:', 0.14458140592957527)
 


In [75]:
data.shape

(93758, 13)

In [78]:
sample = np.random.randint(50000,93758)

In [90]:
str(data.headline.iloc[sample:sample+1,].reset_index().headline[0])

'11 Powerful Women We Met Around the World in 2017'

In [91]:
unseen_doc = []
sentence = str(data.headline.iloc[sample:sample+1,].reset_index().headline[0])
words = word_extraction(sentence)
bag_vector_sample = numpy.zeros(len(vocab))
for w in words:
    for i,word in enumerate(vocab):
                if word == w: 
                    bag_vector_sample[i] += 1
                    
print("{0} \n{1}\n".format(sentence,numpy.array(bag_vector_sample)))
unseen_doc.append(numpy.array(bag_vector_sample))
unseen_doc = pd.DataFrame(unseen_doc)

11 Powerful Women We Met Around the World in 2017 
[0. 0. 0. ... 0. 0. 0.]



In [92]:
for i in range(len(y.columns.tolist())):
    print y.columns.tolist()[i], ": ", rfc.predict(unseen_doc).tolist()[0][i]

emotion_0 :  0.119060494705
emotion_1 :  0.0167655286866
emotion_2 :  0.0792426110321
emotion_3 :  0.0281758337285
emotion_4 :  0.14484107792
emotion_5 :  0.388476963806
emotion_6 :  0.0172055476529
emotion_7 :  0.0787725225225
emotion_8 :  0.308666311048
emotion_9 :  0.995010589537


In [93]:
for i in range(len(y.columns.tolist())):
    print y.columns.tolist()[i], ": ", knn.predict(unseen_doc).tolist()[0][i]

emotion_0 :  0.110955712663
emotion_1 :  0.0997498302639
emotion_2 :  0.071455697698
emotion_3 :  0.118831554058
emotion_4 :  0.0762347887317
emotion_5 :  0.376408210974
emotion_6 :  0.0202768864336
emotion_7 :  0.136714137638
emotion_8 :  0.214354451496
emotion_9 :  0.987406345846


In [142]:
dict1 = []
for i in range(len(y.columns.tolist())):
    dict1.append(str(y.columns.tolist()[i]) + ","+ str(regression_model.predict(unseen_doc).tolist()[0][i]))

In [152]:
dict2 = pd.DataFrame(dict1)
dict2
dict2 = dict2[0].str.split("," ,expand=True)


#### Linear Regression Model: 
0.02359541855770604
#### KNN : 
0.021858531106878996
#### Random Forest Regressor: 
0.020903782940572626